add homework
MastersAcademy/frontend-course-2019 pull request #102
Opened 2019-11-22 15:47 UTC by TupotaValentyn

2019-11-24 10:14 UTC, powerbot15 reviewed
Добавь ссылку на гитхаб пейджес

2019-12-04 19:19 UTC, TupotaValentyn commented
> Добавь ссылку на гитхаб пейджес

Fixed

2019-12-06 08:47 UTC, TArch64 requested changes

2019-12-06 08:47 UTC, TArch64 commented on package.json
> +        "eslint": "^6.7.1",
Відміни всі зміни в package.json

2019-12-06 08:51 UTC, TArch64 commented
І в тебе там конфлікти. Порезолвай всі

2019-12-14 18:03 UTC, TArch64 requested changes

2019-12-14 18:03 UTC, TArch64 commented on homeworks/valentyn.tupota_TupotaValentyn/homework_4/src/IsValid.js
> +    // eslint-disable-next-line
Навіщо так тяжко робити з сінгелтоном? Це ж не джава і тут не треба ці костилі. Просто зроби інстанс класу і заекспорть його

2019-12-14 18:03 UTC, TArch64 commented on homeworks/valentyn.tupota_TupotaValentyn/homework_4/src/index.js
> +            .minLength(formData[item]) && IsValid
Не роби купу цієї супер універсальної логіки з цими всими циклами та іншим. У тебе є статична кількість філдів у формі і статична кількість валідацій. Просто дістань кожен філд руками і виклич для нього валідатори. В цьому всьому, що ти накодив тяжко розібратись

2019-12-14 18:09 UTC, TupotaValentyn commented on homeworks/valentyn.tupota_TupotaValentyn/homework_4/src/IsValid.js
> +    // eslint-disable-next-line
Яж це і роблю нище.

![image](https://user-images.githubusercontent.com/39265433/70852727-8bb08b80-1ead-11ea-968d-b70f88cd9b78.png)

2019-12-14 19:14 UTC, TArch64 commented on homeworks/valentyn.tupota_TupotaValentyn/homework_4/src/IsValid.js
> +    // eslint-disable-next-line
ну да. І при цьому в тебе є ще логіка в конструкторі, яка не використовується

2019-12-14 19:15 UTC, TArch64 commented on homeworks/valentyn.tupota_TupotaValentyn/homework_4/src/IsValid.js
> +    // eslint-disable-next-line
О, і ще прибери коменти, які відключають eslint

2020-01-21 18:33 UTC, TArch64 commented
ping

2020-02-11 15:46 UTC, closed without merging