Finished Homework markup 1
MastersAcademy/frontend-course-2019 pull request #11
Opened 2019-11-02 15:43 UTC by AlexKuskov

2019-11-06 10:41 UTC, TArch64 requested changes

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.html
> +        <div class="greeting__text-wrapper">
Слово wrapper/wrap/container зазвичай нічого особливо не робить (і якщо що, то майже всі елементи є враппером і сенсу додавати це в назву немає). Якщо трохи класи поренеймити, то і без цього слова можна обійтись. Типу щось просто `section` та `greeting__text`?  У і якщо ти в класі вказуєш слово секція, то це з сематичної точки зору це може бути тег section

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.html
> +            <button class="greeting__hire-button primary-button">Hire</button>
Зазвичай для таких компонентів як кнопка роблять базовий клас, який вішають на всі кнопки. І потім уже штуки типу `greeting__hire-button primary-button`.  Ну і якщо продовжувати тему бему, то вийде `button button--primary greeting__hire-button`. Тобто блок кнопка і модифікатор primary

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.html
> +        </div>
Структура цих штук однакова. Можна попробувати через : before / :after. У і називається не дуже. `header-underlines` клас каже що це щось відноситься до хедера. як варіант можна подумати над такимось щось
```
<header class="section__header">
  <h2 class="section__header-title">
  <div class="section__divider">
```

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.html
> +                    <input class="form__input active-input" placeholder="Your Name....." type="text">
`active-input` у тебе на всіх інпутах. Можна або зробити його базовим класом для всіх філдів, бо `active-input` нічого не розказує про себе або просто перенести всі його властивості в `form__input` та `form__textarea`

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +.chosen-item {
Якщо я правильно зрозумів призначення цього класу, то це додається на активний елемент списку або кнопку. Думаю краще робити через модифікатор до окремого класу `navigatiom__item--active`.  І для  такого зазвичай використовують слово active

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  padding: 0 calc((100% - 1200px) / 2);
Це для того щоб відцентрувати контент? Тяжко якось. Краще
```css
max-width: 1200px;
margin-left: auto;
margin-right: auto;
```
І ще якісь падінги, якщо потрібно. Останніх 2 строки вирівнюють блок по центру, а перша обмежує в ширині

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  padding: 0 calc((100% - 1200px) / 2);
І подумай над варіантом, щоб не додавати до кожної секції цей клас, а зробити один елемент з такими властивостями, а всі інші всередину нього покласти і хай розтягуються на всю його ширину

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  line-height: 38px;
line-height зазвичай вказують не в пікселях, а в значенях типу 1.7, 1.4 etc. Ця штука більш універсальна і не буде проблем при зміні розміру шрифта

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  font-weight: 900;
Розміри фонтів та жирність зазвичай беруться з одного набіру. Їх також можна в кастомні проперті закинути

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +}
Дуже багато копіпасту. Зроби щось з цим

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  font-size: .938em;
`font-size: .938em;` Думаю краще використовуй звичайні пікселі. Бо тяжко зрозуміти що це таке і який там буде розмір шрифта

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  margin-bottom: 18px;
Зазвичай використовують розміри і відступи кратні якомусь числу. Наприклад то може бути 4 або 5. Тоді не буде таких штук типу 18, 17, 20, 30 і це все буде більш інтуїтивно і консистентно

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  cursor: pointer;
Зроби базовий клас кнопки і повинось туди спільні властивості. Так буде менше дублювання

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  height: 805px;
Дуже багато точних розмірів. Краще використовувати відносні (%). Потім при респонсів буде менше проблем

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  height: 805px;
Вистота майже завжди контентом задається. Десь екран зміниться, полізе один елемент і там негарно буде

2019-11-06 10:41 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +}
Зазвичай задають бокс сайзінз для всіх однаковий і в самому верху
```
*, *:before, *:after {
  box-sizing: border-box;
}
```

2019-11-06 13:36 UTC, AlexKuskov commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  padding: 0 calc((100% - 1200px) / 2);
Так, спочатку я добавив враппер для всіх секцій, і дав йому властивості які ти запропонував (ширину 1200 і марджіни), але коли я дійшов до "About me" секції, я помітив, що білі поля виглядають по краям.
![Untitled](https://user-images.githubusercontent.com/24815257/68302223-4200a400-00aa-11ea-944e-83e740482edb.png)

Мені це здалось не дуже гарним, і я вирішив додати "padding: 0 calc((100% - 1200px) / 2);", щоб вся секція мала однорідний бекграунд.

Але в будь-якому випадку, якщо необхідно, то я виправлю як потрібно

2019-11-06 14:02 UTC, AlexKuskov commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.html
> +        </div>
> Структура цих штук однакова. Можна попробувати через : before / :after.

Так, структура ліній однакова, але перша лінія має кружечки по боках
![image](https://user-images.githubusercontent.com/24815257/68304146-d7e9fe00-00ad-11ea-937c-378cbc16e8a8.png)

Тому я добавив верхню лінію і :before, :after - кружечки для неї.
А от на рахунок нижньої лінії я не впевнений, як краще її реалізувати. Добавити хтмл елемент, чи добавити до section__header-title чи section__header псевдоелемент :after?

2019-11-06 14:08 UTC, AlexKuskov commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  margin-bottom: 18px;
> Зазвичай використовують розміри і відступи кратні якомусь числу.

А як вибрати таке число / такі числа?

2019-11-06 14:15 UTC, AlexKuskov commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  font-size: .938em;
Тобто, у випадках, коли в em число після крапки виходить більшим аніж двохзначне, то потрібно описувати розмір в пікселях?

2019-11-06 14:58 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  font-size: .938em;
Ні. Просто використовуй пікселі) по ем навіть у девтулз не дуже зрозуміло який там розмір

2019-11-06 14:59 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.html
> +        </div>
Краще окремим елементом для більшої консистентності

2019-11-06 15:07 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  padding: 0 calc((100% - 1200px) / 2);
Ок, хай тут залишаються падінги

2019-11-06 15:11 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
> +  margin-bottom: 18px;
Там у дизайнерів є якісь стайлгайди по яких вони дивляться і думають, але зазвичай беруть число, яке краще ділиться на частини

2019-11-08 08:11 UTC, TArch64 requested changes

2019-11-08 08:11 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +const formInputs = document.querySelectorAll('.form__input');
якщо достаєш елемент з дому по класові, то ЗАВЖДИ додавай префікс js до класу. І такий клас має використовуватись тільки в js. В іншому викпадку штось може випадково клас порефакторити і переназвати, а в нього js впаде. Це не хорошо

2019-11-08 08:11 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +    const emailPattern = /^\S+@\S+\.\S+$/;
Додай ці регекси на верхній рівень. В ідеалі у тебе має бути окремий файл з регулярками, а ле в цьому випадку і вистачить просто винести їх наверх

2019-11-08 08:11 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +    const emailPattern = /^\S+@\S+\.\S+$/;
Регулярку на пошту сам писав?

2019-11-08 08:11 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +    const isInputEmailValid = formInputs[1].value.match(emailPattern);
Не роби таких штук з масивами елементів. Краще зроби на кожен інпут окремий унікальний клас. Клас 'form__input' виглядає так що його можна використати будь де. Якщо дістаєш щось js то скоріше всього тобі потрібен унікальний ідентифікатор

2019-11-08 08:11 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +sendMessageButton.addEventListener('click', (event) => {
краще слухай submit івент у форми. це більш зручно для юзера буде, бо той же сабміт трігериться ентером

2019-11-08 08:11 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +    if (isInputNameValid && isInputEmailValid && messagesTextarea.value) {
Все розбивай на функції. Функція має робити мінімум речей. Чим простіше вона, тим простіше вона буде у використанні. тобто тут має бути ще мінімум одна функція для валідації

2019-11-08 08:11 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +Email: ${formInputs[1].value}
`formInputs[1].value` що тут за значення лежить? а хз. якщо з виразу не зрозуміло що там лежить, то клади в константу

2019-11-08 08:11 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +const formInputs = document.querySelectorAll('.form__input');
І якщо і доставати декілька елеметів з дому таким способом, то уже
```js
const [ nameInputEl, emailInputEl ] = document.querySelectorAll('.form__input');
```
Але краще унікальні селектори, бо мінімальна правка в домі потягне за собою правки в js. Також тяжко зрозуміти де цей селектор використовується

2019-11-08 08:11 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +    event.preventDefault();
Ну і в тебе тут щось страшне з вирівнюванням

2019-11-08 08:12 UTC, TArch64 commented
Ну і в тебе там лінтер валиться
```
homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/style.css
   7:2   ✖  Unexpected whitespace at     no-eol-whitespace                     
            end of line                                                        
  17:5   ✖  Expected double colon        selector-pseudo-element-colon-notation
            pseudo-element notation                                            
  17:15  ✖  Expected double colon        selector-pseudo-element-colon-notation
            pseudo-element notation                                            
  56:22  ✖  Expected double colon        selector-pseudo-element-colon-notation
            pseudo-element notation                                            
  57:22  ✖  Expected double colon        selector-pseudo-element-colon-notation
            pseudo-element notation                                            
  68:22  ✖  Expected double colon        selector-pseudo-element-colon-notation
            pseudo-element notation                                            
  72:22  ✖  Expected double colon        selector-pseudo-element-colon-notation
            pseudo-element notation                                            
 284:17  ✖  Expected double colon        selector-pseudo-element-colon-notation
            pseudo-element notation                                            
 297:17  ✖  Expected double colon        selector-pseudo-element-colon-notation
            pseudo-element notation
```

2019-11-08 09:35 UTC, AlexKuskov commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +    const emailPattern = /^\S+@\S+\.\S+$/;
Та ні) Просто коли я гуглив регулярку на емейл, там були різні - короткі, довгі і дуже довгі. Я вибрав коротшу для більшої лаконічності в коді) 
Але як я розумію, вона не підходить, так що я поставлю якусь більш складнішу, яка більш гнучка в перевірці пошти

2019-11-08 11:06 UTC, AlexKuskov commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +    event.preventDefault();
там проблема, коли я добавляю спейси для того щоб вирівняти код - потім в алерті текст з відступами, типу такого:
Name: name
        Email: email@gmail.com
        Messages: sdaf

2019-11-08 12:51 UTC, AlexKuskov commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +    event.preventDefault();
а, я знаю, я створю функцію, яка буде прибирати спейси

2019-11-09 19:02 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.html
> +            <form class="form js-form">
Це не просто форма. У неї є назва і призвання. як я казав серектори мають бути унікальні. Старайся уникати загальних назв в таких селекторах. Назви краще якось типу `js-feedback-form` і інші типу 'js-feedback-name' etc

2019-11-09 19:27 UTC, TArch64 requested changes

2019-11-09 19:27 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +    return removeExtraWhitespaces(alertOutput);
Для чого ти тут видаляєш пробіли?

2019-11-09 19:29 UTC, TArch64 commented
А так то все. Пофіксь оці вот штуки бігоменько і я замержу

2019-11-09 19:39 UTC, AlexKuskov commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +    return removeExtraWhitespaces(alertOutput);
![image](https://user-images.githubusercontent.com/24815257/68534096-31b22880-0339-11ea-85e4-ca065a0199c3.png)
тому що якщо не видаляти, то виходять ось такі негарні отступи перед Email i Messages

2019-11-09 20:14 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +    return removeExtraWhitespaces(alertOutput);
Бо ти юзаєш тесплейт стрінг і він рахує відступи в коді також. Просто замість переносу в коді юзай символ переносу строки. Не пам'ятаю точно, але він /n був

2019-11-09 20:23 UTC, AlexKuskov commented on homeworks/alexandr.kuskov_AlexKuskov/homework_markup_1/index.js
> +    return removeExtraWhitespaces(alertOutput);
окей, тоді приберу функцію

2019-11-09 20:25 UTC, merged