Homework JS 4
MastersAcademy/frontend-course-2019 pull request #124
Opened 2019-12-03 07:33 UTC by andreyzagoruy-dev

https://andreyzagoruy-dev.github.io/frontend-course-2019/homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/dist/

2019-12-06 09:18 UTC, TArch64 requested changes

2019-12-06 09:18 UTC, TArch64 commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/dist/index.html
> +              <div class="c-form__row">
Для чого додаєш префікси c та l?

2019-12-06 09:18 UTC, TArch64 commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/dist/index.html
> +    <script src="./js/main.js"></script>
Замість DOMContentLoaded юзай атрибут defer. Погугли що це таке

2019-12-06 09:18 UTC, TArch64 commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +            case 'minLength':
Просто знайди в домі елементи та руцями викличи для них валідації. Роби прості речі просто. В тому що ти зробив ніхто не захоче розбиратись

2019-12-06 09:18 UTC, TArch64 commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    form.classList.remove('c-form--valid');
розбивай все на функції. Функція має робити одну дію (задачу)

2019-12-06 09:18 UTC, TArch64 commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    const forms = document.querySelectorAll('.js-form');
Знайди конкретну форму, знайди конкретні елементи всередині цієї форми і виклич для них валідацію. В цьому всьому тяжко і больно робиратись і це все точно оверхед для того щоб провалідувати одну єдину форма зі статичною кількість філдів

2019-12-06 09:18 UTC, TArch64 commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/validator.js
> +        return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(text);
У тебе є прекрасний метод pattern. Чому його тут не використовуєш?

2019-12-06 10:39 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/dist/index.html
> +              <div class="c-form__row">
naming convension:
"c-" - компонент,
"l-" - общие лайаут классы
для удобства

2019-12-06 10:39 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/dist/index.html
> +    <script src="./js/main.js"></script>
Спасибо, забыл за него

2019-12-06 10:41 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    const forms = document.querySelectorAll('.js-form');
Я не понимаю, чем плохо делать валидатор универсальный на любую форму. Сейчас чтобы добавить валидацию в какой-то модалке - достаточно просто ее сверстать и в атрибутах указать нужные валидаторы на каждое поле

2019-12-06 10:53 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/dist/index.html
> +              <div class="c-form__row">
<img width="1026" alt="Screenshot 2019-12-06 at 12 52 50" src="https://user-images.githubusercontent.com/55550156/70317915-67a6d780-1827-11ea-9538-233e1195f793.png">

2019-12-12 08:31 UTC, TArch64 commented
ping-ping

2019-12-13 10:36 UTC, TArch64 requested changes

2019-12-13 10:36 UTC, TArch64 commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    );
Спочатку чукни чи є взагалі значення, а потім уже перевіряй на ренж. Якщо там нічого немає, то в ренж воно точно не попаде

2019-12-13 10:36 UTC, TArch64 commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    const numberOfInvalidFields = formToValidate.querySelectorAll('.c-form__field--invalid').length;
не прив'язуй логіку до класів у домі. У тебе тут уже є всі потрібні дані про валідацію в isLastNameValid, isEmailValid та інші.  до того ж робота з домом це тяжка операція для браузера і її потрібно мінімізувати

2019-12-13 11:09 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    const numberOfInvalidFields = formToValidate.querySelectorAll('.c-form__field--invalid').length;
Я понимаю, что флаги нужные у меня есть. Просто так в 1 строчку проверка. Альтернатива писать огромный иф?

2019-12-13 11:20 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    const numberOfInvalidFields = formToValidate.querySelectorAll('.c-form__field--invalid').length;
Касательно классов. Они и так ставятся JSом. Можно название нужного класса вынести вверху как константу и использовать кругом по коду из одного места

2019-12-13 11:23 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    const numberOfInvalidFields = formToValidate.querySelectorAll('.c-form__field--invalid').length;
Касательно медленных операций. Мы тут ограничиваем поиск по ДОМу "formToValidate" элементом, который один раз выбрали вверху. В реальном мире эта операция будет занимать несколько миллисекунд

2019-12-13 11:24 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    );
Спасибо, так логичнее

2019-12-13 11:32 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    const numberOfInvalidFields = formToValidate.querySelectorAll('.c-form__field--invalid').length;
Еще можно вынести эту строчку в отдельный метод "getNumberOfInvalidFields"

2019-12-13 12:27 UTC, TArch64 commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    setFormState(formToValidate, !isFormInvalid);
Ти тут конвертиш значення isValid в isInvalid а потім знову у isValid
```js
const isFormValid = (
        isFirstNameValid
        && isLastNameValid
        && isEmailValid
        && isPhoneValid
        && isAgeValid
    );

    setFormState(formToValidate, isFormValid);
```

2019-12-13 12:31 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    setFormState(formToValidate, !isFormInvalid);
Согласен. Чтобы лучше понимать логику я хочу понять преимущество подхода с ифом перед предложенным мной ранее вариантом с учетом аргументации из прошлого дискашена

2019-12-13 12:34 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    setFormState(formToValidate, !isFormInvalid);
<img width="638" alt="Screenshot 2019-12-13 at 14 34 09" src="https://user-images.githubusercontent.com/55550156/70800737-a8699800-1db5-11ea-820a-3566dff523de.png">

2019-12-13 12:45 UTC, TArch64 commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    setFormState(formToValidate, !isFormInvalid);
Ну тут насправді іфа немає. Можливо це трохи вкусовщина, але не дуже подобається, що логіка зав'язана на класах в домі, коли в джс уже є всі необхідні дані для цього

2019-12-13 12:53 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_4/src/js/main.js
> +    setFormState(formToValidate, !isFormInvalid);
Видимо вкусовщина :) я изменения запушил

2019-12-13 13:18 UTC, merged