Homework 4
MastersAcademy/frontend-course-2019 pull request #126
Opened 2019-12-03 23:16 UTC by darkwoolf10

2019-12-07 10:33 UTC, TArch64 commented
Для початку пофіксь еррори, які лінтер кидає

2019-12-07 10:47 UTC, TArch64 requested changes

2019-12-07 10:47 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/ValidationForm.js
> +export default class ErrorState {
Чому у тебе 2 класа з одною назвою? І здається тут має бути не ErrorState

2019-12-07 10:47 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/ValidationForm.js
> +        return !(minLength === true && maxLength === false);
Чому люди пишуть `minLength === true`? Можна ж просто `!(minLength && !maxLength);`

2019-12-07 10:47 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/ValidationForm.js
> +        return !(minLength === true && maxLength === false);
І тут думаю треба переписати. З || воно має бути краще

2019-12-07 10:47 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/index.js
> +const errorState = ErrorState.getInstance();
Ну дивись ти такий зробив купу логіки для сінглтона, а в результаті її не використовуєш. Якщо тут замінити на `new ErrorState()`, то нічого не зміниться

2019-12-07 10:47 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/index.js
> +const validationForm = new ValidationForm();
Ну тобто як тут

2019-12-07 10:47 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/index.js
> +                case 'name':
Ти вверху уже знайшов всі елементи форми. Для чого тобі тут цикл на статичну кількість елементів? До того ж ти всеодно руками прописуєш кожен кейс на кожне поле. Просто зроби без цього циклу і у тебе прибереться вся ця лапша і буде простий лінійний код

2019-12-07 10:47 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/regex.js
> +export const regexPhone = /^\+{1}\d{1,2}\({1}\d{3}\){1}\d{3}([-]{1}\d{2}){2}/;
Константи пишемо капсом + у тебе там зайві переноси рядків

2019-12-07 10:47 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/style.scss
> +$body-color: #FFE;
Ну і навіщо тобі тут препроцесори? Для того щоб використати 1  раз зміну та 1 раз вкладеність ти тягнеш купу бібліотек і логіки? Там ще й у тебе тут 50 рядків стилів. Був би ти на реальному проекті, то по руках надавали б. Бібліотеки тягнути бездумно не можна. Це все залежності, які постійно обновляються (або ні, і це ще більша проблема) і за цим потрібно дивитись. Візми просто звичайний css та не страдай всяким

2019-12-07 10:47 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/style.scss
> +$body-color: #FFE;
І якщо що, то у звичайному css уже давно є змінні, які можна використовувати (css custom properties)

2019-12-10 21:04 UTC, darkwoolf10 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/index.js
> +const errorState = ErrorState.getInstance();
Это просто написано в задании, заюзать синглтон, но да ничего не изменится, а в валидаторе не заюзал синглтон, потому что есть правило которое говорит если нету this в методе, то нельзя юзать не статические методы, убрали бы это правило, был бы везде синглтон как указано в задании..

2019-12-10 21:04 UTC, darkwoolf10 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/index.js
> +const validationForm = new ValidationForm();
Да, мне всё равно синглтон, или нет, это указано было в задании

2019-12-10 21:05 UTC, darkwoolf10 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/style.scss
> +$body-color: #FFE;
1. Это не реальный проект,а учебный и поставил чтобы научится через вебпак ставить препроцесор, думаю меня б не взяли на реальный проект не умел бы я этого делать...

2019-12-10 21:09 UTC, darkwoolf10 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/style.scss
> +$body-color: #FFE;
Да, я знаю про переменные в CSS, но уже уточнил, что это потому что хотел настроить webpack и как по мне не стоит наказывать желание, попробовать что-то новое и заюзать как можно больше, потому что это опыт, особенно на учебном проекте, а лучше сказать что в самой реализации не так и лучше высказывать субективную точку зрения...В заданиях обговорено задача, а как нужно сделать не написано, так что реализовываю как смогу. Может моя точка зрения тоже сомнительная...

2019-12-10 21:10 UTC, darkwoolf10 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/regex.js
> +export const regexPhone = /^\+{1}\d{1,2}\({1}\d{3}\){1}\d{3}([-]{1}\d{2}){2}/;
Хорошо, исправлю

2019-12-10 21:11 UTC, darkwoolf10 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/ValidationForm.js
> +        return !(minLength === true && maxLength === false);
Ну это более наглядно, плюс там не строе сравнение

2019-12-10 21:11 UTC, darkwoolf10 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/ValidationForm.js
> +        return !(minLength === true && maxLength === false);
Тут дело вкуса, но если нужно перепишу

2019-12-10 21:12 UTC, darkwoolf10 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/ValidationForm.js
> +export default class ErrorState {
ДА, тут должен быть ValidationForm

2019-12-10 21:41 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/index.js
> +const errorState = ErrorState.getInstance();
Сінгелтон не завжди клас (в js). Якщо що то теж є сінгелтоном
```
const someObject = {}
```

2019-12-10 21:46 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/ValidationForm.js
> +        return !(minLength === true && maxLength === false);
ну там і так true лежить. А так додається додаткових операцій. Якщо нормально називати константи, то з наглядністю все ок. Бо minLength не каже що там булеан, тому воно і не зрозуміло (по назві там має бути число, яке говорить мінімальну довжину). Якщо замінити наприклад на isLessThanMin, то це багато чого змінює. Ну і замінити ще І на АБО, бо тут тяжко розібратись в цій умові

2019-12-10 21:48 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/index.js
> +const errorState = ErrorState.getInstance();
Сінгелтон каже про те, що є тільки один такий інстанс об'єкта. І у всяких джавах це реалізується через те, як зробив ти, але тут можна набагато простіше. Якщо тобі прям потрібно клас, то краще вже
```js
class SomeObject { ... }
export const someObject = new SomeObject();
```

2019-12-10 21:48 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/index.js
> +const errorState = ErrorState.getInstance();
Це прибере цей костиль з getInstance і всякими перевірками

2019-12-13 10:51 UTC, TArch64 commented
ping-ping

2020-02-10 15:46 UTC, TArch64 commented
закрито через відсутність активності

2020-02-10 15:46 UTC, closed without merging