Finish homework 7
MastersAcademy/frontend-course-2019 pull request #138
Opened 2019-12-09 20:36 UTC by MrCartoon

https://mrcartoon.github.io/frontend-course-2019/homeworks/sviat.safronov_MrCartoon/homework_7/dist/app.html

2019-12-10 10:24 UTC, TArch64 requested changes

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/dist/app.css
> +form {
Хоть це і домашка по js, але стилі правильно пишемо і тут. На теги стилі не вішаємо

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/dist/app.css
> +form {
Для чого тобі стильки стилів на форму? Просто додай до інпутів і лейблів display block і вони всі будуть в колонку

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/dist/app.html
> +  <script src="app.js" type="text/javascript"></script>
`type="text/javascript"` це дефолтне значення і його вказувати не потрібно. Додай краще defer (почитай що він робить)

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/package.json
> +    "webpack": "^4.41.2"
Тут зазвичай залишають тільки те, що буде в продакшин білді. Вебпак закидують в devDependencies

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/package.json
> +    "build": "node_modules/webpack/bin/webpack.js --progress --hide-modules"
вебпак має бути доступним через `webpack --progress --hide-modules` всередині скріптів

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +type SubmitEvent = Event & {
Зроби окремий файл з цим типом і інтерфейсом

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +    const firstName = (event.target.querySelector('#first-name') as HTMLInputElement);
Дужечки на початку та в кінці можна не писати

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +        || !isValid.maxLength({ text: firstName.value, length: 20 })) firstName.classList.add('error');
Винось вирази в константи та функції. Виглядає цей іф дуже не читабельним. Тут можна зробить метод аля validateFirstName

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +        result.classList.add('no-display');
Консоль логи поприбирай. таке не пускають в прод. Ну і замість if + add/remove юзай https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle
```js
someEl.classList.toggle('invalid', isInvalid)
```

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +    if (allFields.map((dom) => dom.classList.contains('error')).includes(true)) {
Зберігай результат валідації у константу і дивись в неї. Робота з домом для браузера це одна з найтяжчих операцій + ти прив'яхуєш логіку до певного класу в темплаті, хоча в тебе у цьому методі уже є всі потрібні дані

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/validator.ts
> +    minLength: ({ text, length }: { text: string, length: number }): boolean => text.length >= length,
Замість ітералій в типах роби інтерфейси. Бо читати дуже тяжко + багато копіпасту

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/tsconfig.json
> +    "target": "es5",
зроби в таргет новішу версію. Зараз es5 мало кому потрібно. Хоча б es6 (можна і просто esnext)

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/validator.ts
> +    email: ({ text }: { text: string }): boolean => /(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,})
Винеси регулярки в окремий файл

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/validator.ts
> +    email: ({ text }: { text: string }): boolean => /(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,})
Використовуй звичайні функції замість стрілочних. Тоді ти зможеш стучатись до контейсту і перевикористовувати методи (наприкад викликати pattern в email)

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/validator.ts
> +    pattern: ({ text, pattern }: { text: string, pattern: string }): boolean => text.includes(pattern),
Краще зроби не через об'єкт з параметрами, а просто через 1-2 аргументи. Так набагато простіше виглядає

2019-12-10 10:24 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +    target: HTMLElement;
У Event уже має бути пропертя target

2019-12-10 10:49 UTC, MrCartoon commented on homeworks/sviat.safronov_MrCartoon/homework_7/dist/app.css
> +form {
> Взяти за основу Homework 4

Я просто скопіпастив, а тут оказується треба фіксити заапрувлиний код зі старих домашок.

2019-12-10 10:52 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/dist/app.css
> +form {
Ну у кожного ментора свої вимоги) а насправді потрібно привчатись писати одразу правильно

2019-12-15 14:07 UTC, MrCartoon commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +    target: HTMLElement;
Так, але target не `HTMLElement`, і мені-б прийшлось всюди використовувати `as HTMLElement`, щоб не падав метод `querySelector`.

2019-12-15 14:37 UTC, TArch64 requested changes

2019-12-15 14:37 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/regex.ts
> +const emailRegex = /(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))/;
Константи в UPPER_CASE іменуються. Ну і можна просто `export const EMAIL_REGEX` писати

2019-12-15 14:37 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +    const email = (event.target.querySelector('#email') as HTMLInputElement);
https://stackoverflow.com/a/43035645

querySelector підтримує дженеріки. Це безпечніше ніж кастить тип

2019-12-15 14:37 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +const callback = (event: types.SubmitEvent) => {
Імпортити через зірочку, коли можна тільки окремий модуть вважається поганою практикою, бо це викликає проблети з webpack tree-shaking, що збільшує розмір непотрібного коду у бандлі

2019-12-15 14:38 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +    if (allFields.map((dom) => dom.classList.contains('error')).includes(true)) {
Отетово не пофікшено

2019-12-15 14:38 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +        result.classList.add('no-display');
Отетово не пофікшено

2020-01-13 16:11 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +        || !isValid.maxLength({ text: firstName.value, length: 20 })) firstName.classList.add('error');
@MrCartoon

2020-01-13 16:12 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +        result.classList.add('no-display');
@MrCartoon

2020-01-13 16:13 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +    if (allFields.map((dom) => dom.classList.contains('error')).includes(true)) {
@MrCartoon ну і чим менше всякого всередині умови іф, тим простіше розібратись в ньому. Розбивай це діло на константи

2020-01-13 16:16 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +        || !isValid.maxLength({ text: firstName.value, length: 20 })) firstName.classList.add('error');
@MrCartoon

2020-01-13 16:16 UTC, TArch64 commented
там ще не все пофікшено. заменшенив тебе в коментах

2020-02-10 15:45 UTC, TArch64 commented
ping

2020-02-10 15:58 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +        || !isValid.maxLength({ text: firstName.value, length: 20 })) firstName.classList.add('error');
тут не пофікшено

2020-02-10 15:59 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +        result.classList.add('no-display');
і тут також

2020-02-10 15:59 UTC, TArch64 commented on homeworks/sviat.safronov_MrCartoon/homework_7/src/app.ts
> +    if (allFields.map((dom) => dom.classList.contains('error')).includes(true)) {
і тут також

2020-02-25 12:26 UTC, closed without merging