Home work js 7
MastersAcademy/frontend-course-2019 pull request #141
Opened 2019-12-10 15:02 UTC by LeraB

Demo:

2019-12-13 11:13 UTC, TArch64 requested changes

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/index.css
> +form {
Не вішай стилі на теги. Для цього є класи

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/index.css
> +.col-12 {
Зроби колонки через флекс. Так все набагато простіше
```css
.row {
  display: flex;
  padding: 10px;
}

.col-6 {
  flex-basis: 50%;
  flex-grow: 6;
  flex-shrink: 0;
}

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/index.html
> +<script src="dist/index.js"></script>
Додавай до скриптів атрибут defer. Почитай що це таке

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/index.css
> +  float: left;
Верстка через флот? Зараз не 2007 рік. Юзай флекс або грід

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/package.json
> +    "lodash": "^4.17.15"
Для чого тобі в проекті лодеш?

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/index.ts
> +    if ((minLength({text: firstName.value, length: 2})) && (maxLength({text: firstName.value, length: 20})) && !(firstName.value === '')) {
Великі умови розбивай наконстанти.
замість
```js
    if (isValid) {
        secondName.classList.remove('error');
    } else {
        secondName.classList.add('error');
    }
```
Роби
```js
secondName.classList.toggle('error', !isValid);
```

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/index.ts
> +    // eslint-disable-next-line no-useless-escape
Для чого лінтер відключила?

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/index.ts
> +    const regexEmail = '^(([^<>()/\\[\\]\\\\.,;:\\s@\"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$'
Винось регулярки на глобальний рівень. Бо так вони будуть перестворюватись на кожен виклик метода, хоч і завжи вони однакові. регулярки зазвичай пишуть через літерал `/some-regexp-here/` замість звичайних лапок.

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/index.ts
> +function isValidAge() {
Пиши які типи повертає функція. Якщо у тебе назва isValidAge, то ця функція має повертати булеан і казати чи валідний вік. а у тебе тут всередині валідація + рендер результатів валідації. Переназви функцію

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/index.ts
> +secondName.addEventListener('change', () => {
```js
secondName.addEventListener('change', isValidSecondName);
```

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/index.ts
> +secondName.addEventListener('change', () => {
І інші також

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/index.ts
> +    isValidFirstName();
У тебе тут є всі дані про валадацію. Не зав'язуй логіку на класах в домі. Просто зроби щоб функції-валідатори повертали чи валідний філд

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/validate.ts
> +    // eslint-disable-next-line no-useless-escape
Не відключай лінтер

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/validate.ts
> +interface FieldPattern {
винось інтерфейси в окремі файли

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/validate.ts
> +    return field.text.match(field.pattern) !== null;
просто `field.patters.test(field.text)`

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/validate.ts
> +    return !((field.text === '') || (!field.text.replace(/\s/g, '').length));
`!((field.text === '') || (!field.text.replace(/\s/g, '').length));`
Якось дуже багато дужок спрости. І коли ти робиш `!(come condition)`, то дуже тяжко зрозуміти що тут відбувається. переформулюй умови і спрощуй їх

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/tsconfig.json
> +    "jsx": "react",
не думаю що тут тобі потрібен jsx та allowJs

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/webpack.config.js
> +                test: /\.tsx?$/,
`test: /\.ts$/,` Ти ж не будеш тут писати на реакті з тайпскріптом

2019-12-13 11:13 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/webpack.config.js
> +        extensions: [ '.tsx', '.ts', '.js' ],
`extensions: [ '.ts' ],` У тебе там немає js та реакта

2019-12-13 15:39 UTC, LeraB commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/index.ts
> +    // eslint-disable-next-line no-useless-escape
Не пропускав регексп

2019-12-13 15:46 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/index.ts
> +    // eslint-disable-next-line no-useless-escape
Ти гуглала чому?

2019-12-13 15:54 UTC, LeraB commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/validate.ts
> +    // eslint-disable-next-line no-useless-escape
він не пускає мої регекспи

2019-12-13 15:55 UTC, LeraB commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/validate.ts
> +interface FieldPattern {
тобто один інтерфейс - один файл?

2019-12-13 18:59 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/validate.ts
> +    // eslint-disable-next-line no-useless-escape
Тому що потрібно фіксити те, що він каже)

2019-12-13 18:59 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/validate.ts
> +interface FieldPattern {
Ага. І можна під них папку зробити. типу models

2019-12-14 13:14 UTC, LeraB commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/index.ts
> +    isValidFirstName();
не зрозуміла, що маєш на увазі. Можна, будь ласка, детальніше

2019-12-14 13:18 UTC, TArch64 commented on homeworks/valeriia.briantseva_LeraB/homework_js_7/src/index.ts
> +    isValidFirstName();
Я про те, що функції типу isValidFirstName  можуть повертати значення чи валідне поле. І якщо всі виклики функцій повернуть true, то форма валідна. У тебе тут вже є всі необхідні дані і тобі не потрібно діставати їх з дому

2019-12-14 16:48 UTC, merged