Completed homework 7 js
MastersAcademy/frontend-course-2019 pull request #165
Opened 2019-12-19 00:35 UTC by AlexKuskov

https://alexkuskov.github.io/frontend-course-2019/homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/

2020-01-29 10:50 UTC, TArch64 requested changes

2020-01-29 10:50 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/src/index.ts
> +    element.setAttribute('style', 'border-color: rgb(255, 0, 0); color: rgb(255, 0, 0);');
1. стилі краще змінювати через element.style.someCssPropertyInCamelCase бо так ти ресетиш весь атрибут і можеш видалити стилі, які хтось в іншому місці поклад.
2. Якщо тобі потрібно змінювати вигляд елемента через css, то краще використовуй classList і класи. css зручніше писати у css файлах

2020-01-29 10:50 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/src/index.ts
> +    element.setAttribute('style', 'border-color: rgb(0, 0, 0); color: rgb(0, 0, 0);');
Тоді ці 2 функції можна буде замінити на одну і просто через classList.toggle додавати\прибирати класс

2020-01-29 10:50 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/src/index.ts
> +        setValidInputStyle(element);
і ця штука вже буде не потрібна

2020-01-29 10:50 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/src/index.ts
> +    validationTextSpanEl.setAttribute('style', 'visibility: visible;');
зроби класс типу hidden і додавай його коли потрібно. це більш надійно, ніж писати стилі в джаваскрипті

2020-01-29 10:50 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/src/index.ts
> +    event.preventDefault();
зазвичай `event.preventDefault();` пишуть першою строкою

2020-01-29 10:50 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/src/regex-patterns.ts
> +// eslint-disable-next-line
Для чого тут eslint-disable?

2020-01-29 10:50 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/tsconfig.json
> +    "jsx": "react",
react?

2020-01-29 10:50 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/webpack.config.js
> +      extensions: [ '.tsx', '.ts', '.js' ],
Які з цих екстеншинів ти використовуєш?

2020-01-29 10:50 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/webpack.config.js
> +          test: /\.tsx?$/,
у тебе тут є tsx?

2020-02-01 15:20 UTC, AlexKuskov commented
element.classList.toggle() не дуже підходить в випадку форми, так як після кліку на сабміт, стан поля буде мінятися вне залежності від того, буде це поле валідним чи не валідним.

2020-02-01 15:22 UTC, AlexKuskov commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/src/regex-patterns.ts
> +// eslint-disable-next-line
На скільки я пам'ятаю, на момент написання цього файла, у мене eslint ругався на RegExp

2020-02-01 15:25 UTC, AlexKuskov commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/tsconfig.json
> +    "jsx": "react",
я не додивився, що конфігураціонні файли по дефолту пихають реакт файли

2020-02-04 14:47 UTC, TArch64 commented
@AlexKuskov можна зробити отак
```js
inputEl.classList.toggle('field--invalid', isInvalid);
inputEl.classList.toggle('field--valid', !isInvalid);
```
Тоді у тебе є 2 класа які переключаються між валідним та не валідним станами філда. А в css просто описуєш як вони будуть виглядатм

2020-02-04 14:52 UTC, TArch64 requested changes

2020-02-04 14:52 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/src/index.ts
> +    element.classList.add('form__input--invalid');
```js
element.classList.toggle('form__input--invalid', !isInputValid)
```

2020-02-04 14:52 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/src/validation.ts
> +    maxLength: Function;
Використання типу Function вважають поганою практикою і майже завжди заборонять eslint. вказуй конкретний тип функції
```ts
numberRange: (value: number, min: number, max: number) => boolean
```
Але у тебе тут інтерфейс і їх можна описувати отак. тобто як методи класу, але без тіла функції
```ts
interface Validation {
  numberRange(value: number, min: number, max: number): boolean;
}
```

2020-02-04 14:52 UTC, TArch64 commented on homeworks/alexandr.kuskov_AlexKuskov/homework_4_js/src/index.ts
> +    element.classList.add('form__input--invalid');
toggle приймає 2 аргумента https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle

2020-02-06 10:10 UTC, merged