Added homework 7js
MastersAcademy/frontend-course-2019 pull request #180
Opened 2020-01-21 08:59 UTC by schikk

https://schikk.github.io/frontend-course-2019/homeworks/maksym.shykunov_schikk/homework_7_JS/

2020-01-29 15:21 UTC, TArch64 requested changes

2020-01-29 15:21 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_7_JS/src/index.ts
> +    const inputs: NodeListOf<Element> = document.querySelectorAll('.validate');
для чого тобі inputs шукати в домі по класі, якщо нижче в тебе є всі ці елементи?

2020-01-29 15:21 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_7_JS/src/index.ts
> +            }
```ts
inputName.classList.toggle('invalid', !validate)
```

2020-01-29 15:21 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_7_JS/src/index.ts
> +        }
якщо у тебе пройшла валідація, то не має на всіх інпутах уже бути видалений класс invalid? і тут цей цикл нічого не робить

2020-01-29 15:21 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_7_JS/src/index.ts
> +        validInput(emailValid, emailInput);
В назві функцій мають бути дієслова. Знайди тут дієслово `validInput`

2020-01-29 15:21 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_7_JS/src/index.ts
> +        validInput(emailValid, emailInput);
це стосується і інших функцій. Якщо немає, то додай дієслово, бо функція означає екшин. в булеан мають бути префікси is, has etc

2020-01-29 15:21 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_7_JS/src/main.css
> +.input-wrapper input {
не пиши стилі на теги. Ніколи. завжди роби клас

2020-01-29 15:21 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_7_JS/src/main.css
> +.input-wrapper input {
в назвах слово враппер зазвичай нічого не значить і його можна переназвати нормально. коли є слово враппер, то завжди можна перепроектувати компонент щоб його не було. Наявність цього класу говорить, бо просто неправильно обраний рутовий елемент блока. Наприклад
```css
.field {
 // .input-wrapper styles
}

.field__label {
  // .input-wrapper label styles
}

.field__input {
  // .input-wrapper input styles
}
```

2020-01-29 15:21 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_7_JS/src/main.css
> +.input-wrapper input.invalid {
пиши стилі інпута біля інших стилів інпута

2020-01-29 15:21 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_7_JS/webpack.config.js
> +                test: /\.tsx?$/,
tsx? у тебе там є десь реакт?

2020-01-29 15:21 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_7_JS/webpack.config.js
> +        extensions: ['.tsx', '.ts', '.js'],
які з цих екстеншинів є в сорсах?

2020-02-10 15:26 UTC, TArch64 commented
ping

2020-02-11 08:41 UTC, schikk commented
сорі за затримку, перезалив https://github.com/schikk/frontend-course-2019/commit/7808eafa38919f529bfe31750084bf2d566be59e

2020-02-11 09:01 UTC, merged