homework_7
MastersAcademy/frontend-course-2019 pull request #185
Opened 2020-01-26 19:12 UTC by NataliKokovina

2020-01-29 15:49 UTC, TArch64 requested changes

2020-01-29 15:49 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/index.html
> +    <script src="./dist/main.js"></script>
використовуй для підключення скріптів атрибут defer

2020-01-29 15:49 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/src/validation.ts
> +    value?: string;
Для чого об'єкт з одним полем? Не можна просто строку передати?

2020-01-29 15:49 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/src/validation.ts
> +    email: HTMLInputElement;
у тебе вже є такий інтерфейс. Винести типи в окремі файли і перевикористовуй їх

2020-01-29 15:49 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/src/validation.ts
> +        cleared(form.firstName);
краще зроби метод toggleFieldError який буде додавати або прибирати клас. Ну і можна тоді буде використовувати classList.toggle

2020-01-29 15:49 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/src/validation.ts
> +    && isValidAge(form.age, 18, 120)) {
Чому не можна покласти перевірку в змінні і перевикористати результат?

2020-01-29 15:49 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/tsconfig.json
> +      "jsx": "react",
react?

2020-01-29 15:49 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/webpack.config.js
> +        test: /\.tsx?$/,
tsx? У тебе тут є реакт?

2020-01-29 15:49 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/webpack.config.js
> +    extensions: [ '.tsx', '.ts', '.js' ],
Які з цих розширень є у тебе в сорсах?

2020-02-02 22:13 UTC, NataliKokovina commented
Дякую за коментарі. Все виправила. Перевір будь ласка

2020-02-04 14:43 UTC, TArch64 requested changes

2020-02-04 14:43 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/src/helper.ts
> +        item.classList.toggle('invalid');
Мені не дуже подобається ця перевірка. Думаю її можна зробити простіше знаючи, що classList.toggle приймає ще один аргумент force
https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle

2020-02-04 14:43 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/src/index.ts
> +document.querySelector('.form_button').addEventListener('click', submitForm);
Коли ти працюєш з формами, то краще слухати не клік на кнопку сабміта, а івент submit у форми. Цей івент викликається в деяких інших випадках і дає юзеру додаткові зручності. Наприклад сабміт форми ентером. в результаті ти слухаєш сабміт форми і опрацьовуєш його. А замість того щоб слухати кнопку ти їх даєш type="submit" і вона трігерить сабміт у форми

2020-02-04 14:43 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/src/interface.ts
> +    [key: string]: HTMLInputElement;
опиши кожеш філд у цьому інтерфейсі. `[key: string]` потрібно коли ключи динімічно додаються на основі якикихось даних, а у тебе тут статична кількість і типів інпутів

2020-02-04 14:43 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/src/validation.ts
> +    return reName.test(name) && name.length >= min && name.length <= max;
що таке reName?

2020-02-04 14:43 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/src/validation.ts
> +    return reName.test(name) && name.length >= min && name.length <= max;
не скорочуй. Є виключення часто з слів, які часто використовуються і загальновідомі, але в інших випадках скорочення тільки тяжче роблять розуміння код, бо тобі ще постійно думати як це розшифровується. Всеодно код буде переписаний агліфаєм і можна робити назви які душі завгодно. Головне щоб це було зрозуміло

2020-02-04 14:43 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/src/validation.ts
> +        return reAge.test(numberRange)
Не думаю що є сенс перевіряти регуляркою вік. Просто приведи до числа, а потім подивись чи це число у валідному ренжі

2020-02-04 14:43 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/src/validation.ts
> +        toggleSubmitMes(document.querySelector('.successfullFormMessages'), document.querySelector('.invalidFormMessages'));
не дуже подобається, що робота функції зав'язана по порядку аргументів. Зроби краще окремі функції toggleSuccessfullMessage та toggleInvalidFormMessage

2020-02-10 07:43 UTC, NataliKokovina commented
Дякую. Все виправила. Перевір ще раз будь ласка

2020-02-10 15:16 UTC, TArch64 approved these changes

2020-02-10 15:16 UTC, TArch64 commented on homeworks/nataliia.kokovina_NataliKokovina/homework_7/src/validation.ts
> +    return false;
можна ж просто 
```js
return numberAge === 0 || numberAge >= min && numberAge<= max;
```

2020-02-10 15:18 UTC, merged