Homework Angular Components&Templates
MastersAcademy/frontend-course-2019 pull request #187
Opened 2020-01-29 15:38 UTC by andreyzagoruy-dev

GitHub Pages: https://andreyzagoruy-dev.github.io/ng-list/dist/demo-components/

2020-02-03 14:56 UTC, powerbot15 requested changes

2020-02-03 14:56 UTC, powerbot15 commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_8/components/product-list/product-list.component.html
> +</ng-template>
Вот тут плохо, вместо того чтобы юзать темплейт для продукта, надо сделать новый компонент собственно продукта, чтобы юзать его в списках. В текущем исполнении этот код плохо читается и соответственно разобраться в нем сложнее чем должно быть

2020-02-04 11:37 UTC, andreyzagoruy-dev commented on homeworks/andrey.zagoruy_andreyzagoruy-dev/homework_8/components/product-list/product-list.component.html
> +</ng-template>
Согласен, готово!

2020-02-11 08:44 UTC, powerbot15 approved these changes

2020-02-11 08:44 UTC, merged