Add homework_markup_5
MastersAcademy/frontend-course-2019 pull request #190
Opened 2020-01-31 14:38 UTC by Omega24v

2020-02-04 15:05 UTC, TArch64 commented
В завданні було сказано підключати іконки через спрайти. У тебе тут трохи не те. Сенс спрайта в тому, що багато іконок в одному файлі

2020-02-05 20:21 UTC, Omega24v commented
> В завданні було сказано підключати іконки через спрайти. У тебе тут трохи не те. Сенс спрайта в тому, що багато іконок в одному файлі

Додав спрайт.

2020-02-06 08:53 UTC, TArch64 requested changes

2020-02-06 08:53 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/index.html
> +                </a href="#">
атрибут на закривающому тегі?

2020-02-06 08:53 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/index.html
> +                    <svg class="item__icon" width="30" height="30" viewBox="0 0 30 30" preserveAspectRatio="none">
коли використовується use то на svg не вказується viewBox. він вказується на символі всередині спрайту

2020-02-06 08:53 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/style.css
> +  transition: .3s ease-out;
які проперті ти даєш транзішин? На всі?

2020-02-06 08:55 UTC, TArch64 requested changes

2020-02-06 08:55 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/img/settings.svg
> +	<path d="M27,18c-4.963,0-9,4.037-9,9s4.037,9,9,9s9-4.037,9-9S31.963,18,27,18z M27,34c-3.859,0-7-3.141-7-7s3.141-7,7-7
Для чого тобі ці файли з іконками, якщо вони лежать у спрайті?

2020-02-06 20:27 UTC, Omega24v commented on homeworks/anton.sergienko_omega24v/homework_markup_5/img/settings.svg
> +	<path d="M27,18c-4.963,0-9,4.037-9,9s4.037,9,9,9s9-4.037,9-9S31.963,18,27,18z M27,34c-3.859,0-7-3.141-7-7s3.141-7,7-7
Логічно. Забув видалити.

2020-02-06 20:27 UTC, Omega24v commented on homeworks/anton.sergienko_omega24v/homework_markup_5/index.html
> +                    <svg class="item__icon" width="30" height="30" viewBox="0 0 30 30" preserveAspectRatio="none">
Добре, виправлю.

2020-02-06 20:29 UTC, Omega24v commented on homeworks/anton.sergienko_omega24v/homework_markup_5/style.css
> +  transition: .3s ease-out;
Виходить, що так) 

А як задати transition конкретно до --primary-color і --secondary-color?

2020-02-06 20:29 UTC, Omega24v commented on homeworks/anton.sergienko_omega24v/homework_markup_5/index.html
> +                </a href="#">
Пофіксив.

2020-02-06 21:58 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/style.css
> +  transition: .3s ease-out;
Кастомні проперті не входять у список тих, які можна анімувати. Просто вкажи на класі, який описує твою іконку, транзішин на поля в які передаються кастомні проперті

2020-02-06 23:02 UTC, Omega24v commented on homeworks/anton.sergienko_omega24v/homework_markup_5/style.css
> +  transition: .3s ease-out;
А можешь будь-ласка приклад показати? Бо я щось не дуже розумію.

Кастомні передаю так 
` <circle style="fill: var(--primary-color)" cx="56.098" cy="56.098" r="56.098"/>
        <path  style="fill: var(--secondary-color)" d="M70.201,58.294h-10.01v36.672H45.025V58.294h-7.213V45.406h7.213v-8.34 c0-5.964,2.833-15.303,15.301-15.303L71.56,21.81v12.51h-8.151c-1.337,0-3.217,0.668-3.217,3.513v7.585h11.334L70.201,58.294z"/>`

> Просто вкажи на класі, який описує твою іконку, транзішин на поля в які передаються кастомні проперті
?
`.css-variables circle {}
`

2020-02-07 10:41 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/style.css
> +  transition: .3s ease-out;
ну в твоєму випадку або без транзішина, або замість `.css-variables circle {}` нормальний клас + інлайнові стилі в svg винести в клас теж. але потірбно дивитись щоб клас був унікальним

2020-02-07 10:56 UTC, TArch64 requested changes

2020-02-07 10:56 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/img/sprite.svg
> +  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 42 42" id="add">
symbol підтримує атрибут xmlns. Для цього є тег svg

2020-02-07 10:56 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/img/sprite.svg
> +<svg width="0" height="0" class="hidden">
якщо ти підключаєш спрайт як окремий файл, то не потрібно `width="0" height="0" class="hidden"`. його і так не видно на сторінці і замість всієї імеджі ти дістаєш тільки її кусок

2020-02-07 10:56 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/img/sprite.svg
> +  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 58.365 58.365" id="home">
пиши айдішку першим атрибутом. По іконках зазвичай орієнтуються по ід, а коли цей атрибут отсанній, то його довше потрібно шукати

2020-02-07 10:56 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/index.html
> +            <li class="navbar__nav__item item">
у тебе тут є li. А де його парент ul?

2020-02-07 10:56 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/index.html
> +            <li class="navbar__nav__item item">
Простіше зробити просто nav + a

2020-02-07 10:56 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/index.html
> +            <li class="navbar__nav__item item">
item може бути багато. Вказуй конкретнішу назву

2020-02-07 10:56 UTC, TArch64 commented on homeworks/anton.sergienko_omega24v/homework_markup_5/index.html
> +                    <svg class="item__icon" width="30" height="30" preserveAspectRatio="none">
preserveAspectRatio="none" можна винести в символ

2020-02-10 15:44 UTC, TArch64 commented
ping

2020-02-10 15:58 UTC, Omega24v commented
> ping

Обновив.

2020-02-25 12:31 UTC, merged