Homework_Angular_Components&Templates
MastersAcademy/frontend-course-2019 pull request #204
Opened 2020-02-11 19:05 UTC by LeraB

2020-02-12 14:53 UTC, powerbot15 requested changes
В `product-list` у тебя идет дублирование разметки для продуктов. Оптимальное решение - сделать отдельній компонент для списка продуктов, а нынешний `product-list` переименовать в `products` например, импортить туда компонент списка и использовать для фейворитс и для обычных продуктов. Просто через инпут передавать нужные списки. Второй вариант неоптимальный, но проще - сделать отдельный компонент `product` и итерировать его в списках, передавая туда каждый продукт

2020-02-25 21:22 UTC, LeraB commented
Done

2020-02-25 21:22 UTC, LeraB reviewed
done

2020-02-28 07:47 UTC, powerbot15 approved these changes

2020-02-28 07:48 UTC, merged