fixed homework markup 1 + homework 2
MastersAcademy/frontend-course-2019 pull request #41
Opened 2019-11-06 20:18 UTC by YulyKo

2019-11-06 22:11 UTC, YulyKo commented
Лінка на [github page](https://yulyko.github.io/frontend-course-2019/homeworks/julia.kotenko_YulyKo/homework_1/index.html)
Рекомендую перегляд при 1920х1080

2019-11-08 07:21 UTC, powerbot15 commented
У тебя много предупреждений выдал линтер, надо все исправить
```
/home/circleci/tmp/homeworks/julia.kotenko_YulyKo/homework_1/script.js
   1:5    error    'element' is assigned a value but never used                           no-unused-vars
   1:5    error    'element' is never reassigned. Use 'const' instead                     prefer-const
   1:38   error    Strings must use singlequote                                           quotes
   3:10   error    'onSubmit' is defined but never used                                   no-unused-vars
   4:5    error    'checkEmptyInputs' was used before it was defined                      no-use-before-define
   4:23   error    Missing semicolon                                                      semi
   8:9    error    'email' is never reassigned. Use 'const' instead                       prefer-const
   8:49   error    Missing semicolon                                                      semi
   9:23   error    Missing semicolon                                                      semi
  13:9    error    'name' is never reassigned. Use 'const' instead                        prefer-const
  13:47   error    Missing semicolon                                                      semi
  14:22   error    Missing semicolon                                                      semi
  18:9    error    'message' is never reassigned. Use 'const' instead                     prefer-const
  18:53   error    Missing semicolon                                                      semi
  19:25   error    Missing semicolon                                                      semi
  23:9    error    'email' is never reassigned. Use 'const' instead                       prefer-const
  23:34   error    Missing semicolon                                                      semi
  24:9    error    'name' is never reassigned. Use 'const' instead                        prefer-const
  24:30   error    Missing semicolon                                                      semi
  25:9    error    'message' is never reassigned. Use 'const' instead                     prefer-const
  25:36   error    Missing semicolon                                                      semi
  26:15   warning  Expected '!==' and instead saw '!='                                    eqeqeq
  26:29   warning  Expected '!==' and instead saw '!='                                    eqeqeq
  26:46   warning  Expected '!==' and instead saw '!='                                    eqeqeq
  27:9    error    'validationOfEmail' was used before it was defined                     no-use-before-define
  27:28   error    Missing semicolon                                                      semi
  29:75   error    Missing semicolon                                                      semi
  33:10   error    Expected to return a value at the end of function 'validationOfEmail'  consistent-return
  34:9    error    'mailformat' is never reassigned. Use 'const' instead                  prefer-const
  34:36   error    Missing semicolon                                                      semi
  35:9    error    'email' is never reassigned. Use 'const' instead                       prefer-const
  35:32   error    Missing semicolon                                                      semi
  37:16   error    'validationName' was used before it was defined                        no-use-before-define
  37:31   error    Unexpected use of 'name'                                               no-restricted-globals
  37:36   error    Missing semicolon                                                      semi
  38:12   error    Unnecessary 'else' after 'return'                                      no-else-return
  39:15   error    Strings must use singlequote                                           quotes
  39:44   error    Missing semicolon                                                      semi
  43:10   error    Expected to return a value at the end of function 'validationName'     consistent-return
  44:9    error    'name' is never reassigned. Use 'const' instead                        prefer-const
  44:30   error    Missing semicolon                                                      semi
  46:16   error    'showResultMessage' was used before it was defined                     no-use-before-define
  46:35   error    Missing semicolon                                                      semi
  47:12   error    Unnecessary 'else' after 'return'                                      no-else-return
  48:15   error    Strings must use singlequote                                           quotes
  48:98   error    Missing semicolon                                                      semi
  54:9    error    'email' is never reassigned. Use 'const' instead                       prefer-const
  54:32   error    Missing semicolon                                                      semi
  55:9    error    'name' is never reassigned. Use 'const' instead                        prefer-const
  55:30   error    Missing semicolon                                                      semi
  56:9    error    'message' is never reassigned. Use 'const' instead                     prefer-const
  56:36   error    Missing semicolon                                                      semi
  57:11   error    Unexpected string concatenation                                        prefer-template
  57:102  error    Missing semicolon                                                      semi

✖ 54 problems (51 errors, 3 warnings)
  42 errors and 0 warnings potentially fixable with the `--fix` option.

```

2019-11-08 09:10 UTC, YulyKo commented
Окей, зара пофіксю

2019-11-09 20:52 UTC, TArch64 requested changes

2019-11-09 20:52 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/.eslintrc.js
> +module.exports = {
Використовуй глобальний конфіг лінтера

2019-11-09 20:52 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/script.js
> +    const message = getMessageValue();
У тебе часто викликаються функції getEmailValue etc в кожній є робота з домом. Краще достань один раз елемент і поклади в константу наверху. пошук в домі не сама швидка операція, особливо коли це потрібно робити часто

2019-11-09 20:52 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/script.js
> +    alert(`User ${name}(${email})
краще заюзай символ новох строки замість такого /n. Виглядає це не дуже

2019-11-09 20:52 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/script.js
> +    if (/^[A-Za-z\s]+$/.test(name)) {
Регулярки винось в константи

2019-11-09 20:52 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/script.js
> +function validationOfEmail() {
just `validateEmail`

2019-11-09 20:52 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/script.js
> +        validationName(name);
Трохи дивно зроблена валідація. Зроби декілька функцій, які роблять перевірки і повертають помилку, або нічого. а потім просто 
```js
const validationError = validateEmail() || validateName();
if (validationError) showValidationError(validationError);
```

2019-11-09 20:52 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +  grid-template-rows: 100vh;
Використовуй краще просто процентики. Бо vw vh також рахує скролл бари, іноді куски інтерфейсу.

2019-11-09 22:42 UTC, TArch64 requested changes

2019-11-09 22:42 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +  justify-content: space-between !important;
Для чого ти кидаєш !important?

2019-11-09 22:42 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +  margin-top: 2rem;
Для відступів використовуй просто пікселі. Відступи зазвичай статичні і однорідні по аплікейшину. А так не зрозуміло скільки тут відступ і чи зним все впорядку

2019-11-09 22:42 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +.list-item {
Якщо по бему, то більше list__item бо то є елемент ліста, а не окремий блок

2019-11-09 22:42 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +.image-profile0 {
кажись опечатка вкінці image-profile0

2019-11-09 22:42 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +  padding: 3% 2vw;
Відступи зазвичай статичні і майже завжди це пікселі, особливо в кнопках. Вони мають бути передбачуваними

2019-11-09 22:42 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +.image-profile1 {
Чому у тебе існують класи image-profile0 та image-profile1 ?

2019-11-09 22:42 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +.form_input,
1. для розділення слів використовуй або - або _. Не мішай.
2. по бему більше form__input точно як і . з form__textarea

2019-11-09 22:42 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +  transition: all 1s;
Вказуй транзішин для окремих полів. Там більш зрозуміло що саме анімується

2019-11-09 22:42 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +  transition: all 1s;
І якщо потрібно вказуй will-change

2019-11-09 22:42 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +  -webkit-transition: 1s;
вказуй уже для всіх однакоий транзішин

2019-11-09 22:42 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/text.css
> +.text--xl {
зазвичай text--xl від text відрізняється тільки розміром, а у тебе тут куча всього. Якщо ти хочеш все одним класом, то назви його типу title, а якщо хочеш хелпери, то роби купу хелперів

2019-11-09 22:42 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/text.css
> +  width: 87%;
зазвичай в хелперах для тексту тільки фонт сайз. Хтось захоче використати цей фонт сайз а тут ще ширина задана

2019-11-12 19:36 UTC, YulyKo commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +  justify-content: space-between !important;
без нього воно не відпрацьовувало як потрібно

2019-11-12 19:37 UTC, YulyKo commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +.image-profile0 {
там раніше була розбивка на image-profile0 і image-profile1

2019-11-12 19:43 UTC, YulyKo commented on homeworks/julia.kotenko_YulyKo/homework_1/text.css
> +.text--xl {
це має бути саме текст. У тайтла свій шрифт і font-width. Я так позначила розмір самого тексту, як на мене, це ліпше чим small, big тощо.

2019-11-12 19:43 UTC, YulyKo commented on homeworks/julia.kotenko_YulyKo/homework_1/text.css
> +  width: 87%;
без ширини не ставало так як у макеті

2019-11-12 21:01 UTC, YulyKo commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +  -webkit-transition: 1s;
Що включає це включає у себе?

2019-11-13 08:23 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/text.css
> +  width: 87%;
Я про те, якщо це хелпер, то ширина має бути в іншому класі (або можна якось без ширини?). Якщо це не хелпер, то називати його text--l не найкраща ідея

2019-11-13 08:25 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/text.css
> +.text--xl {
Я про те, що це не хелпер тексту, а повноцінний компонент, а ти назвала його як хелпер. Йому більше потрібно щось типу main-title, title, app-title etc

2019-11-13 08:28 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +  -webkit-transition: 1s;
У тебе цей транзішин буде врятлі працювати, бо у нього тільки одна пропертя і все інше до дефолту скидиується на сафарі. Там потрібно копі паст нормального транзішина і спереді префікс дописати і зазвичай префікси пишуть біля властивості без префіксу

2019-11-13 08:30 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +.image-profile0 {
Ніколи не називай так класи. Потім буде тяжко розібратись де який компонент і для чого він і чому він взагалі існує

2019-11-13 08:30 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/style.css
> +  justify-content: space-between !important;
чому воно не правильно відпрацьовувало?

2019-11-13 11:27 UTC, TArch64 commented on package.json
> +    "eslint": "^6.6.0",
Не чіпай, будь-ласка, глобальні конфіги. Хай еслінт залишається там де і був. Його туди не просто так поклали

2019-11-13 20:40 UTC, TArch64 requested changes

2019-11-13 20:40 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/script.js
> +        showValidationError(validationError);
В чому сенс виводити в консоль true\false ? Я говорив про те, що тут validateEmail та validateName повертали стрінгу з еррором і тут був вивід її в ui через алерт

2019-11-13 20:40 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/script.js
> +let message = '';
якщо хочеш зберігати якось контекст, то зроби уже краще клас

2019-11-13 20:40 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/script.js
> +Your message: ${message} was sended to Jhon Smith`);
просто юзай \n . фізичний перенос строки ненадійно і виглядає недуже

2019-11-13 20:40 UTC, TArch64 commented on homeworks/julia.kotenko_YulyKo/homework_1/script.js
> +    const nameFormat = /^[A-Za-z\s]+$/;
винось резулярки глобально, а не в функції і то є константа. Тобішь UPPER_CASE

2019-11-17 16:39 UTC, TArch64 commented
У тебе там CI валиться на лінтерах

2019-11-18 12:23 UTC, merged