Home work 3
MastersAcademy/frontend-course-2019 pull request #42
Opened 2019-11-06 20:49 UTC by YaroslavO

2019-11-08 07:26 UTC, powerbot15 commented
Линтер ругается, надо поисправлять
```
homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.css
 220:1   ✖  Expected empty line before rule       rule-empty-line-before       
 223:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 232:1   ✖  Expected empty line before rule       rule-empty-line-before       
 239:1   ✖  Expected empty line before rule       rule-empty-line-before       
 247:1   ✖  Expected empty line before rule       rule-empty-line-before       
 249:11  ✖  Unexpected leading zero               number-leading-zero          
 258:1   ✖  Expected empty line before rule       rule-empty-line-before       
 261:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 263:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 271:1   ✖  Expected empty line before rule       rule-empty-line-before       
 274:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 283:1   ✖  Expected empty line before rule       rule-empty-line-before       
 291:1   ✖  Expected empty line before rule       rule-empty-line-before       
 294:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 296:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 303:1   ✖  Expected empty line before rule       rule-empty-line-before       
 305:16  ✖  Expected numeric font-weight          font-weight-notation         
            notation                                                           
 312:1   ✖  Expected empty line before rule       rule-empty-line-before       
 317:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 324:1   ✖  Expected empty line before rule       rule-empty-line-before       
 332:1   ✖  Expected empty line before rule       rule-empty-line-before       
 341:12  ✖  Unexpected leading zero               number-leading-zero          
 345:9   ✖  Unexpected leading zero               number-leading-zero          
 353:1   ✖  Expected empty line before rule       rule-empty-line-before       
 363:1   ✖  Expected empty line before rule       rule-empty-line-before       
 370:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 372:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 374:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 382:1   ✖  Expected empty line before rule       rule-empty-line-before       
 385:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 392:1   ✖  Expected empty line before rule       rule-empty-line-before       
 395:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 401:1   ✖  Expected empty line before rule       rule-empty-line-before       
 411:1   ✖  Expected empty line before rule       rule-empty-line-before       
 422:1   ✖  Expected empty line before rule       rule-empty-line-before       
 432:1   ✖  Expected empty line before rule       rule-empty-line-before       
 433:12  ✖  Unexpected leading zero               number-leading-zero          
 433:19  ✖  Unexpected leading zero               number-leading-zero          
 433:26  ✖  Unexpected leading zero               number-leading-zero          
 442:1   ✖  Expected empty line before rule       rule-empty-line-before       
 445:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 447:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 449:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 451:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 453:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 460:1   ✖  Expected empty line before rule       rule-empty-line-before       
 467:1   ✖  Expected empty line before rule       rule-empty-line-before       
 475:1   ✖  Expected empty line before rule       rule-empty-line-before       
 479:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 486:1   ✖  Expected empty line before rule       rule-empty-line-before       
 495:1   ✖  Expected empty line before rule       rule-empty-line-before       
 498:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 505:1   ✖  Expected empty line before rule       rule-empty-line-before       
 513:1   ✖  Expected empty line before rule       rule-empty-line-before       
 516:3   ✖  Expected empty line before            declaration-empty-line-before
            declaration                                                        
 525:1   ✖  Expected empty line before rule       rule-empty-line-before       
 532:1   ✖  Expected empty line before rule       rule-empty-line-before       
 541:1   ✖  Expected empty line before rule       rule-empty-line-before       
 548:1   ✖  Expected empty line before rule       rule-empty-line-before

```

2019-11-08 10:07 UTC, YaroslavO commented
> Линтер ругается, надо поисправлять
> 
> ```
> homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.css
>  220:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  223:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  232:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  239:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  247:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  249:11  ✖  Unexpected leading zero               number-leading-zero          
>  258:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  261:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  263:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  271:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  274:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  283:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  291:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  294:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  296:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  303:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  305:16  ✖  Expected numeric font-weight          font-weight-notation         
>             notation                                                           
>  312:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  317:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  324:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  332:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  341:12  ✖  Unexpected leading zero               number-leading-zero          
>  345:9   ✖  Unexpected leading zero               number-leading-zero          
>  353:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  363:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  370:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  372:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  374:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  382:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  385:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  392:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  395:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  401:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  411:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  422:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  432:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  433:12  ✖  Unexpected leading zero               number-leading-zero          
>  433:19  ✖  Unexpected leading zero               number-leading-zero          
>  433:26  ✖  Unexpected leading zero               number-leading-zero          
>  442:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  445:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  447:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  449:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  451:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  453:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  460:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  467:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  475:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  479:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  486:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  495:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  498:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  505:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  513:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  516:3   ✖  Expected empty line before            declaration-empty-line-before
>             declaration                                                        
>  525:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  532:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  541:1   ✖  Expected empty line before rule       rule-empty-line-before       
>  548:1   ✖  Expected empty line before rule       rule-empty-line-before
> ```

Я использовал scss. поэтому не стал заморачиваться над отступами.
Чтоб эти ошибки исчезли нужно убрать normalize.css 
Линтер не понимает что код сгенерирован.

2019-11-08 10:58 UTC, TArch64 commented
Просто підключи нормалайз через CDN 
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha256-l85OmPOjvil/SOvVt3HnSSjzF1TUMyT9eV0c2BzEGzU=" crossorigin="anonymous" />
```

2019-11-08 12:26 UTC, TArch64 requested changes

2019-11-08 12:26 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.js
> +const form = document.getElementsByClassName('article__form')[0];
Просто юзай `querySelector`. З ним простіше

2019-11-08 12:26 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.js
> +const name = document.getElementsByClassName('article__input-name')[0];
Селектор для js має бути унікальним і до таких селекторів краще додавати префікс js щоб потім при рефакторингу стилів знати що це в js використовується і не поломати нічого

2019-11-08 12:26 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.js
> +form.onsubmit = (event) => {
Використовуй краще addEventListener. там більше опшинів і в випадку чого можна повісити декілька колбеків на один івент

2019-11-08 12:26 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_3/index.html
> +                const {responseType = '', onprogress, method = "GET"} = options;
Навіщо method передавати? у тебе тут окремий метод для гет запита і ти завжди знаєш що method = "GET"

2019-11-08 12:26 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_3/index.html
> +                    };
xhr.onload = () => resolve({body: xhr.response});

2019-11-08 12:26 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_3/index.html
> +                    xhr.open(method, url);
Тут ти завжди знаєш, що в method лежить `'GET'`. Можна навіть літералом забити

2019-11-08 12:26 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_3/index.html
> +                const {responseType = '', onprogress, method = "GET"} = options;
В responseType не може бути пустої строки. Там завжди якесь значення. Частіше всього юзеру потрібно буде там `application/json`

2019-11-08 12:51 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.js
> +const form = document.getElementsByClassName('article__form')[0];
+

2019-11-08 12:51 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.js
> +const name = document.getElementsByClassName('article__input-name')[0];
+

2019-11-08 12:52 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_3/index.html
> +                    };
+

2019-11-08 12:53 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_3/index.html
> +                const {responseType = '', onprogress, method = "GET"} = options;
Я не знав що по дефолту треба "application/json"
В доці написано
""
An empty responseType string is treated the same as "text", the default type.
Тому вирішив порожню строку.

2019-11-08 12:54 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_3/index.html
> +                const {responseType = '', onprogress, method = "GET"} = options;
Просто хотів крутіший код написати)

2019-11-08 12:55 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_3/index.html
> +                    xhr.open(method, url);
+

2019-11-08 15:54 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.js
> +const form = document.getElementsByClassName('article__form')[0];
Що то за точечка?

2019-11-08 15:55 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_3/index.html
> +                const {responseType = '', onprogress, method = "GET"} = options;
Ну так зазвичай щоб було крутіше, то роблять клас, а в ньому методи get, post, patch, delete etc як відповідають за певний http метод

2019-11-08 15:58 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_3/index.html
> +                const {responseType = '', onprogress, method = "GET"} = options;
В докі написано про text, але зараз на дворі 2019 рік і скоріш всього всі туди будуть ставити application/json. Бо текстом чи xml зараз ніхто і нічого не пересилає. Люди майже завжди використовують json. Думаю можна навіть зробити константу DEFAULT_RESPONSE_TYPE де прописати людський тип респонсу, якщо ніхто нічого не передав

2019-11-08 17:04 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.js
> +const form = document.getElementsByClassName('article__form')[0];
це так гітхаб плюс перетворює

2019-11-09 18:52 UTC, TArch64 requested changes

2019-11-09 18:52 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +<section class="articles__section">
З семантичної точки зору це ні разу не section. Більше сюди підходить main, бо в тебе тут тільки одна секція, в якій весь контент сторінки

2019-11-09 18:52 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +<section class="articles__section">
Якщо дивитись з точки зору БЕМ на `articles__section`, то в цей клас є елементом `articles`, але останнього в тебе немає. Назви якось по іншому клас. щось типу sections

2019-11-09 18:52 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +</nav>
`menu ` по фактом є header сторінки. і трохи не навігацією (лого може не входити в тег навігації). А отой `menu__group ` уже є том самим nav

2019-11-09 18:52 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +            </div>
Для тексту є тег p

2019-11-09 18:52 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +        <div class="article__content_left">
Поменше використовуй назви left right, а first, next, second старайся взагалі не використоувати. Замість таких слів напиши назву, яка буде говорити про контент

2019-11-09 18:52 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +            </div>
Тут у тебе якась магія з 3ма колонками. Зроби просто 2 колонки і щоб перша була в 2 рази більше другої
![image](https://user-images.githubusercontent.com/29049264/68491501-a743c900-0253-11ea-9adb-1f16191510f9.png)

2019-11-09 18:52 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +    <article class="article article__first">
З семантичної точки зору це не article. це є section, бо це частина сторінки, article більше про окрему сутність (наприклад пост в соц мережі)

2019-11-09 18:52 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +    <article class="article article__first">
І не використовуй назви тегів в селекторах. Ти прив'язуєш використання до певних тегів. в один момент вони молжуть (і скоріше всього) зміняться на інші і це буде плутати людей, або хтось може не використовувати цей клас, бо буде думати що він тільки для цього тегу працює, а там просто падінги і фон

2019-11-09 18:52 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +            <div class="article__first_text">
Замість того щоб писати кожен раз новий клас з такими страшними назвами зроби собі класи типу text--regular, text--heading, text--subheading etc, і для кольорів text--primary, text--secondary, text--warning etc

2019-11-09 18:59 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.js
> +const form = document.getElementsByClassName('article__form')[0];
Замість точки нажимай кнопку 
![image](https://user-images.githubusercontent.com/29049264/68533622-aaae8180-0333-11ea-85a6-055a78e29fbd.png)

2019-11-09 19:15 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +<section class="articles__section">
Часу думати не було, тому так понаписував.

2019-11-09 19:17 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +            </div>
Я його не брав бо він додавав margin.

2019-11-09 19:19 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +        <div class="article__content_left">
Знову ж таки все впирається в час

2019-11-09 19:21 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +            </div>
Логічно. Теж так думав

2019-11-09 19:22 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +    <article class="article article__first">
це я один article пропустив)

2019-11-09 19:23 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +            <div class="article__first_text">
Логічно. Теж так думав. Написав як швидше

2019-11-09 19:31 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +            </div>
Ну так маржін можна прибрати. Оберай теги не по стилях, які на них висять, а по тому для чого вони вони використовуються

2019-11-09 19:33 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +<section class="articles__section">
Ми тут не сайтец по дедлайнах для замовників пилимо. А пробуємо вас навчити і показати як потрібно. А в цьому сенсу немає, якщо всі будуть робити як небуть, бо немає часу

2019-11-09 20:01 UTC, TArch64 requested changes

2019-11-09 20:01 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +<section class="articles__section">
`<section class="articles__section">` тут у тебе не секція, а основний контент сторінки в якого є різні секції. Для такого зазвичай використовують main

2019-11-09 20:01 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +<section class="articles__section">
articles__section І цей клас каже що у тебе тут є блок articles, а це його елемент (частина блоку, яка без нього не може існувати), але тут у тебе немає блоку articles

2019-11-09 20:01 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +            </div>
використовуй класи, які для цього робили та переназивай класи за тим як вони використовуються.

2019-11-09 20:01 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +        </section>
У тебе тут секція всередині секції. Щось з цим не так. І я трохи сумнівать про необхідніть <section class="article__content_right">. Скоріш вього він тут не потрібен

2019-11-09 20:01 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +</footer>
Навіщо тобі пустий футер?

2019-11-09 20:01 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +<script src="index.js"></script>
додавай до скріптів defer, щоб він відпрацьовував після відмальовки дому. Без нього іноді можуть не знаходитись елементи в домі

2019-11-09 20:01 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.js
> +const getElement = (selector) => document.querySelector(selector);
Навіщо так тяжко з getElement. Просто заюзай document.querySelector. Ти не так то і багато економиш букв

2019-11-09 20:01 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.js
> +const form = getElement('.article__form');
Використовуй класи, які використовуються тільки в js для селекторів і додавай но назви префікс js- . зміни в логіці мають по мінімуму впливати на стилі та розмітку

2019-11-09 20:01 UTC, TArch64 commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.scss
> +$active_text_color: #FE7E11;
Давай поки без препроцесорів. До того ж тяжко дивитись на ці всі вкладеності. І якщо тобі потрібні змінні, то використовуй css variables. Для цього сас вже не потрібен, а кількість вкладеностей в селекторах робить це все нечитабельним і тяжко зрозуміти що до чого належить і що для чого використовується

2019-11-09 20:25 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +</footer>
хотів пізніше доробити

2019-11-09 20:27 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.js
> +const getElement = (selector) => document.querySelector(selector);
Якщо треба буде змінити querySelector на щось інше то треба буде повсюду його заміняти)
Просто так красивіше

2019-11-09 20:27 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +<script src="index.js"></script>
Ніколи з таким проблем не було)

2019-11-09 20:35 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.scss
> +$active_text_color: #FE7E11;
без препроцесору я б верстав набагато довше)
нажаль в мене немає стільки часу

2019-11-09 20:38 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +<section class="articles__section">
Він там раніше був)

2019-11-09 20:40 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +        </section>
Ну тут версталось тільки для того щоб була форма на другу домашку.
Якщо що можу лишній section убрати

2019-11-09 20:51 UTC, YaroslavO commented on homeworks/yaroslav.olenenko_YaroslavO/homework_2/index.html
> +<script src="index.js"></script>
Насправді давно вже вручну не підключав файли. За мене це робить webpack

2019-11-09 21:02 UTC, closed without merging