Re: Homework 2
MastersAcademy/frontend-course-2019 pull request #49
Opened 2019-11-09 09:50 UTC by batteryfree

https://batteryfree.github.io/frontend-course-2019/homeworks/roman.vlasov_batteryfree/homework_2/

2019-11-11 16:54 UTC, TArch64 requested changes
То тобі на перший час. Як пофіксиш -- далі підемо

2019-11-11 16:54 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +        this.validation = true;
validation це більше про процес. Тут підійде краще isValid, або деякі просто роблять validationError з стрінгою і якщо там щось є, то форма не валідна

2019-11-11 16:54 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +        this.elements.send.addEventListener('click', () => {
Якщо елемент використовується один раз (як у тебе на ініті), то його немає сенсу тримати в пам'яті. І краще слухай сабміт у форми, а не клік на кнопку. Тоді більше є варіантів як відправити запит (наприклад ентером)

2019-11-11 16:54 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +                }
Для всього що ти тут робишщ придумати атрибут placeholdet в інпута

2019-11-11 16:54 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +            editsText: this.el.querySelectorAll('.contact__edit'),
Не роби так. Це не дуже зрочно. Зробюи на кожен інпут окремий клас і шукай кожен інпут окремо. І якщо ти щось дістаєш з дому по класу, то цей клас скоріш всього має бути унікальним  і до класів, які використовуються як селектори в джеес додають префікс js- щоб люди розуміли, що на ньому тримається логіка і ніхто нічого не замал при рефакторингу стилів

2019-11-11 16:54 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +            elem.style.border = '1px solid #a9a9a9';
Замість того щоб змінювати інлайнові стиля навішук клас, а там хай уже css розбирайється сам як його показати. classList.toggle тобі допоможе

2019-11-11 16:54 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +});
Щоб не слухати івенти просто додай атрибут defer до script тегу, де в тебе цей файл підключається

2019-11-11 16:54 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/index.html
> +        <script src="app.js"></script>
<script src="app.js" defer></script>

2019-11-11 16:54 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +                    this.changeStyleInput(element);
Для того щоб показувати стан валідації філда в реальному часі люди використовують change або input івент в інпутів

2019-11-15 12:26 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +        this.validation = true;
fixed

2019-11-15 12:26 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +        this.elements.send.addEventListener('click', () => {
fixed

2019-11-15 12:27 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +            editsText: this.el.querySelectorAll('.contact__edit'),
fixed

2019-11-15 12:27 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +            elem.style.border = '1px solid #a9a9a9';
fixed

2019-11-15 12:27 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +});
fixed

2019-11-15 12:27 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/homework_2/index.html
> +        <script src="app.js"></script>
fixed

2019-11-15 12:34 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +                    this.changeStyleInput(element);
є питання з приводу івенту чендж в інпут майл ... в хромі він не відпрацйовуе якщо відразу надрукувати тільки прогонии та пертейти в інший філд ... чи можна зцим якось боротись ..чи доведеться мириться з цим?

2019-11-16 13:18 UTC, TArch64 requested changes

2019-11-16 13:18 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +        const VALID_MESS = /^/i;
Не всі валідації робляться регулярками. Тут регулярка прям зовсім оверхед `const VALID_MESS = /^/i;`

2019-11-16 13:18 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +            contactSubmit: this.el.querySelector('.js-submit'),
слухай сабміт івент форми, а не кнопку. Для юзера так набагато зручніше. Люди які сабмітять форми ентером будуть кожен раз відчувати біль

2019-11-16 13:18 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +    }
У тебе цей метод називається getValidateData, а насправді він робить валідацію, скидає навіщось element.value в пустий та рендерить втиху інвалідний стан стилів. Не роби так. Розбивай функції за тим що вони роблять. Чим менше задач виконує функція, тим краще.\

Універсальний валідатор ненапишеш, а в цьому ніхто розбиратись не захоче. Зроби окремо для кожного поля. Максимум що зазвичай роблять, так це виносять деякі елементи в хелпери. типу такого
```js
class SendMessage {
  isEmptyField(input) {
    return !input.value.trim()
  }

  isEmail(input) {
    return EMAIL_PATTERN.test(input.value);
  }

  validateEmail() {
    const emailEl = this.elements.contactEmail;

    if ( isEmptyField(emailEl) ) return `Email field is required';
    if ( isEmail(emailEl) ) return 'Email has not valid format';
  }

  validate() {
    const validationError = this.validateEmail() || this.validateName();
    const isValid = !validationError;
  }
}

```

2019-11-16 13:18 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +    const sendMessage = new SendMessage(document.querySelector('.contact__message'));
ти тут забув про префікс для цього класу. І у тебе там скріпт через defer підключений. `document.addEventListener('DOMContentLoaded'` тут зайвий

2019-11-19 11:19 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +        const VALID_MESS = /^/i;
fixed

2019-11-19 11:19 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +            contactSubmit: this.el.querySelector('.js-submit'),
fixed

2019-11-19 11:20 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +    }
Вроде понял...спасибо!

2019-11-19 11:22 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +    const sendMessage = new SendMessage(document.querySelector('.contact__message'));
Да.. забыл).. спасибо

2019-11-19 13:25 UTC, TArch64 commented
Розбий на кожну домашку на окремий пулл реквест. Бо так цей буде перевірятись вічність

2019-11-19 13:25 UTC, closed without merging

2019-11-19 15:36 UTC, batteryfree commented
Разбил..RE: RE HomeWork-2 #82...эт всё из-за пейджес...я уже поднимал вопрос поводу этого...и я сделал как понял...надо бы что-бы еще раз объяснили для тех кто в танке(то есть для меня )