Add homework_3
MastersAcademy/frontend-course-2019 pull request #54
Opened 2019-11-11 14:02 UTC by Chebutalio

2019-11-11 16:34 UTC, TArch64 requested changes

2019-11-11 16:34 UTC, TArch64 commented on homeworks/vitaliy.kyian_Chebutalio/homework_3/index.html
> +                get(URL, { responseType, onprogress }) {
`URL ` коли змінну називають в аппер сейсі, то говорять що це контанта і її не можна змінювати. Тут у тебе просто аргумент функції. Хоч то і абрівіатура, але краще називай не в аппер кейс

2019-11-11 16:34 UTC, TArch64 commented on homeworks/vitaliy.kyian_Chebutalio/homework_3/index.html
> +max-width: 100%" data-cat />
У тебе тут щось з форматування погане сталось

2019-11-11 16:34 UTC, TArch64 commented on homeworks/vitaliy.kyian_Chebutalio/homework_3/index.html
> +                    const promise = new Promise(function (resolve) {
Немає сенсу в константі з назвою проміс (це як назвати змінну variable). Вона ні про що не говорить. До того ж тут можна просто `return new Promise`

2019-11-11 16:34 UTC, TArch64 commented on homeworks/vitaliy.kyian_Chebutalio/homework_3/index.html
> +                    const promise = new Promise(function (resolve) {
`Promise(function (resolve)` при передачі функції літеролом в класі краще юзай стрілочну функцію. Вона не створює свій контекст і з такої функції ти можеш звертатись до контексту класа без всяких костилів

2019-11-11 16:34 UTC, TArch64 commented on homeworks/vitaliy.kyian_Chebutalio/homework_3/index.html
> +                            if (xhr.status !== 200) {
з success статусів є не тільки 200. https://www.restapitutorial.com/httpstatuscodes.html

2019-11-11 16:34 UTC, TArch64 commented on homeworks/vitaliy.kyian_Chebutalio/homework_3/index.html
> +                        xhr.open('GET', URL, true);
Останій аргумент по дефолту true і немає сенсу його передавати

2019-11-11 16:34 UTC, TArch64 commented on homeworks/vitaliy.kyian_Chebutalio/homework_3/index.html
> +                                aletr(`Помилка ${xhr.status}: ${xhr.statusText}`);
Це клас-серсів, який будуть використовувати інші люди для роботи з http і ці люди краще знають як обробити помилку в їхньому ui, ніж цей сервіс. Просто викликай reject проміса і передавай туди необхідну інформацію (наприклад status та statusText)

2019-11-11 16:34 UTC, TArch64 commented on homeworks/vitaliy.kyian_Chebutalio/homework_3/index.html
> +                        };
```js
xhr.onerror = () => reject({ status: xhr.status, statusText: xhr.statusText })
```

2019-11-11 16:37 UTC, TArch64 commented on homeworks/vitaliy.kyian_Chebutalio/homework_3/index.html
> +                    const promise = new Promise(function (resolve) {
https://medium.com/@thejasonfile/es5-functions-vs-es6-fat-arrow-functions-864033baa1a

Ну і стрілочні функції в один рядок простіше виглядають

2019-11-11 16:38 UTC, TArch64 commented
`Add files via upload` І гугли як працювати з гітом (насправді там немає нічого тяжкого, особливо з того що вам потрібно зараз). Зараз ще прокатує, але коли почнеш з кимось ще над проектом працювати, то буде больно

2019-11-13 20:54 UTC, Chebutalio commented
По гіту проходжу відео-уроки і читаю книжку, скоро все буде ок. Все інше наче поправив. Дякую.

2019-11-16 15:30 UTC, Chebutalio commented
https://github.com/Chebutalio/Homework_markup-2

2019-11-16 16:56 UTC, TArch64 commented
По Homework_markup-2: всі ісходніки проекту кладуть в підпапку, а не в рут. Це робиться для того щоб вони не перемішувались з іншими файлами проекту, бо проект це не тільки ісходніки. Є ще купа конфігів, нод модулі, папка з білдом. Щоб ті ж лінтери не конфліктували з 2 останніми, зроби підпапку app, src, main etc де будуть лежати ісходніки проекту (index.html, script.js, style.css) і запускай всі лінтери всередині цієї підпапки, а не глобально

2019-11-16 16:57 UTC, TArch64 commented on homeworks/vitaliy.kyian_Chebutalio/homework_3/index.html
> +                            if (xhr.status !== 200 && xhr.status !== 201) {
Там не тільки 2 статуса) Якщо коротко, то всі статуси, які починаються на 2 вважаються success

2019-11-19 13:26 UTC, TArch64 commented
Добий отанній коммент і я замержу гілку, бо висить уже і так довго

2019-11-19 13:27 UTC, TArch64 commented on homeworks/vitaliy.kyian_Chebutalio/homework_3/index.html
> +                            if (xhr.status !== 200 && xhr.status !== 201) {
Підійде щось таке `const isError = xhr.status >= 400`

2019-11-20 19:11 UTC, merged