Added Homework 3
MastersAcademy/frontend-course-2019 pull request #64
Opened 2019-11-13 11:09 UTC by schikk

https://schikk.github.io/frontend-course-2019/homeworks/maksym.shykunov_schikk/homework_3/index.html

2019-11-13 11:42 UTC, TArch64 requested changes

2019-11-13 11:42 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_3/index.html
> +                        xhr.onerror = () => reject(alert('Loading Error'));
Для чого ти робиш `reject(alert`? `reject` це як throw тільки для проміса. В твоєму випадку більше підходить просто reject і туди щось передати. Наприклад об'єкт з status та statusText

2019-11-13 11:42 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_3/index.html
> +                    // Return it as a Promise
Ці 2 коментаря не несуть ніякої інформативності. Там констуктор і так каже що то є XHR та проміс

2019-11-14 20:08 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_3/index.html
> +                        statusText: 'Loading Error'
ці 2 поля є в об'єкта реквеста

2019-11-15 10:19 UTC, TArch64 requested changes

2019-11-15 10:19 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_3/index.html
> +                    }
Проблема того, що ти тут зробив в тому, що `status, statusText` в даний момент відображають стан запита, коли його ще не відправили, тобто по факту там пусто. Ти його тут кладеш в об'єкт і віддаєш цей об'єкт, коли приходить відповіть на запит, то ці поля змінюються і там вже не пусто, а справжній HTTP статус та текстовка, але в цьому об'єкту значення не змінюються

2019-11-15 10:19 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_3/index.html
> +                    const { status, statusText, response } = xhr;
І `response ` у тебе по ходу не використовується

2019-11-19 13:29 UTC, TArch64 commented on homeworks/maksym.shykunov_schikk/homework_3/index.html
> +                    }
Зроби просто 
```js
xhr.onerror = () => reject({ status: xhr.status, statusText: xhr.statusText });
```

2019-11-19 13:29 UTC, TArch64 commented
Добий цей коммент і я замержу, щоб гілка не висіла

2019-11-20 19:10 UTC, TArch64 commented
Винеси 4ту домашку в окрему гілку

2019-11-20 19:51 UTC, schikk commented
В окрему гілку виніс, але коміти в 4й від 3ї, а в 3й від 4ї, якось можна їх переносить?

2019-11-20 21:15 UTC, TArch64 commented
Потрібно щоб у цьому пулл реквесті не було 4ї домашки. Якщо прибереш її звідси, то я її змержу і в 4й буде все ок

2019-11-21 08:05 UTC, TArch64 commented
Знайди в історії комміт (можеш на гітхабі шукати) де ще немає 4ї домашки, зроби від того комміта нову гілку. Додай всі зміни 3ї домашки в ту гілку і зроби від неї пулл реквест

2019-11-21 08:26 UTC, schikk commented
Я повністю вдалив 4-ту та її pull request, відкловся від мастера зробив гілку для 4ї і залив 4ту. І шось я заплутався) Видалилти цей пул реквест тоді і заново зробити?

2019-11-21 08:40 UTC, closed without merging

2019-11-21 08:41 UTC, TArch64 commented
1. копіруєш хей комміта
![image](https://user-images.githubusercontent.com/29049264/69320055-1ef8f700-0c49-11ea-836e-9bd60a49b598.png)
2. Переходиш в потрібний комміт `git checkout f23078a47b595a4775e8a77eaaae1bbc126c402a`
3. робиш нову гілку `git checkout -b homework_3`
4. Апдейтиш до актуального стану файл з 3ю домашкою
5. комміт, пуш, пулл реквест з нової гілки

2019-11-21 09:13 UTC, schikk commented
дякую! зробив новий пул