HW_1
MastersAcademy/frontend-course-2019 pull request #66
Opened 2019-11-13 15:32 UTC by TsarevskyAndrew

HW_1

2019-11-18 20:46 UTC, TsarevskyAndrew commented
tsarevskyandrew.github.io/frontend-course-2019/homeworks/andrew.tsarevsky_TsarevskyAndrew/homework_3/index.html

2019-11-21 15:51 UTC, TArch64 requested changes

2019-11-21 15:51 UTC, TArch64 commented on homeworks/andrew.tsarevsky_TsarevskyAndrew/homework_3/index.html
> +                    get(URL, { responseType, onprogress }) {
капсом називають константи. Хоч це абрівіатура, але називай її в правильному кейсі, бо буде плутатись з константами

2019-11-21 15:51 UTC, TArch64 commented on homeworks/andrew.tsarevsky_TsarevskyAndrew/homework_3/index.html
> +                                if (xmlRequest.status !== 200) {
success статусом є не тільки 200. https://www.restapitutorial.com/httpstatuscodes.html Якщо коротко всі статус коди, які починаються на 2 є success статусами

2019-11-21 15:51 UTC, TArch64 commented on homeworks/andrew.tsarevsky_TsarevskyAndrew/homework_3/index.html
> +                                    alert(`Error ${xmlRequest.status}: ${xmlRequest.statusText}`);
прокинь через reject статус та статусТекст на верх. Людина яка використовує http client краще знає як йому показати помилку, ніж цей клас

2019-11-21 15:51 UTC, TArch64 commented on homeworks/andrew.tsarevsky_TsarevskyAndrew/homework_3/index.html
> +                                alert('Request failed');
Точно те ж саме з обробкою ерорів

2019-11-21 15:51 UTC, TArch64 commented on homeworks/andrew.tsarevsky_TsarevskyAndrew/homework_3/index.html
> +                        const promise = new Promise((resolve) => {
Немає сенсу називати зміну promise. Це як назвати зміну variable. Це не несе в собі ніякої інформативності. До того ж тут ти робиш зміну і одразу її повертаєш

2019-11-21 15:51 UTC, TArch64 commented on homeworks/andrew.tsarevsky_TsarevskyAndrew/homework_3/index.html
> +                        const promise = new Promise((resolve) => {
Просто `return new Promise`

2019-11-21 15:51 UTC, TArch64 commented on homeworks/andrew.tsarevsky_TsarevskyAndrew/homework_3/index.html
> +                            xmlRequest.open('GET', URL, true);
Останній аргумент по дефолту true і немає сенсу його вказувати

2019-11-26 13:01 UTC, TArch64 commented
Закрито через відсутність активності

2019-11-26 13:01 UTC, closed without merging