RE: RE HomeWork-2
MastersAcademy/frontend-course-2019 pull request #82
Opened 2019-11-19 15:30 UTC by batteryfree

2019-11-20 19:07 UTC, TArch64 requested changes

2019-11-20 19:07 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +/* eslint-disable */
Для чого лінтер відключив?

2019-11-20 19:07 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +            element.preventDefault();
якщо колбеки займають більше 1го рядку, або некрасіво виглядають, то винось в метод класу

2019-11-20 19:07 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +            messageEl: this.formEl.querySelector('.js-contact-message'),
немає сенсу в постфіксі El. Його додають щоб знати що це елемент з дому. У тебе вони всі в об'єкті elements так що постфікс тут зайвий

2019-11-20 19:07 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +    initElements() {
більше щось findElements. Ти їх не інітиш, а шукаєш в домі

2019-11-20 19:07 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +        this.formEl = el;
Поклади вже і елемент форми в elements щоб все разом було

2019-11-20 19:07 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +    }
Краще роби для конкретної перевірки конкретний метод. Так потім зручніше з кастомізаціями. для різних регулярок можуть потребувати різні дії і не факт що там буде потрібна регулярка. Да і ясності більше і коді буде

2019-11-20 19:07 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +        const vErrorName = this.validateName();
Ніколи не скорочуй. Зрозумілість коду завжди важливіша за економію символів

2019-11-20 19:07 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +        this.setValidStyle(this.elements.nameEl, !vErrorName);
ValidStyle звучить начебто ти валідні стилі додаєш. Зазвичай функції з зміною дому називають render + дія. наприклад renderValidationState

2019-11-20 19:07 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +    setValidStyle(input, swKey) {
що таке swKey?

2019-11-21 07:42 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +    setValidStyle(input, swKey) {
swKey (switchKey) мається на увазі включення/вимкнення стилю (наступне імья що приходить на розум це "toggle")... а як би ти назвав двнний параметр/змінну

2019-11-21 07:46 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +    setValidStyle(input, swKey) {
Тогл і свіч це екшини і по назві можна подумати, що це якийсь колбек. В  таких випадках більше підходить щось типу isValid. А взагалі цей пост був про те, що скоротивши назву аргументу взагалі не зрозуміло для чого він і що він таке

2019-11-21 07:47 UTC, powerbot15 commented on homeworks/roman.vlasov_batteryfree/homework_2/app.js
> +    setValidStyle(input, swKey) {
По контексту подойдет `valid` или `isValid`, у тебя получится `setValidStyle(input, isValid)` - что сразу вносит ясность

2019-11-21 11:31 UTC, merged