Make validation with Singleton for form
MastersAcademy/frontend-course-2019 pull request #95
Opened 2019-11-21 20:13 UTC by darkwoolf10

2019-11-22 10:26 UTC, TArch64 requested changes

2019-11-22 10:26 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/ErrorState.js
> +        const input = this.form.querySelector(`input[name=${field}]`);
потім хтось змінить нейм в хтмл і в тебе все впаде да і використання елемента в js так важко шукати. Зроби для кожного інпута унікальтний селектор і передавай сюди просто елемент. Або ти можеш для кожного інпута робити новий інстанс класу, який буде працювати з цим філдом. Краще останій варіант

2019-11-22 10:26 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/ErrorState.js
> +        if (error === true) {
if (error) {

2019-11-22 10:26 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/ErrorState.js
> +            input.style.border = '3px solid green';
додавай або прибирай клас з елемента. css краще знає як показати стейт елемента. В js має бути по мінімуму інлйнових стилів і html

element.classLint.toggle('some-class-name', isActive)

2019-11-22 10:26 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/Singleton.js
> +        this.instance = true;
краще щось типу isCreatedInstance бо плутається з this.instance в статичному методі

2019-11-22 10:26 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/Singleton.js
> +        return this.instance;
можна трохи простіше. І до this.instance ніхто не має стучатись напряму. Тобто це приватний філд. А до приватних філдів\методів додають префікс _
```js
static get instance() {
  if ( this._instance ) this._instance = new this();
  return this._instance
}
```

2019-11-22 10:26 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/Validator.js
> +        const emailPattern = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))/;
Винеси регулярки в окремий файл і імпорть сюди щоб вони при кожному виклику метода не стровювались заново і їх можна було юзати, де вони потрібні без копіпасту

2019-11-22 10:26 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/index.js
> +        switch (field) {
Ідея зі свічом не зручна і громіздка. Напиши на кожний філд окремо функцію і викликай її. цей цикл тільки тяжче робить розуміння того що тут відбувається

2019-11-22 10:26 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/style.scss
> +  .container {
Замість вкладеностей використовуй БЕМ. Унікальні назви зручніші, бо тут, наприклад, хтось може додати всередині ще один елмент .container і в нього буде height: 100%;, хоча йому воно не потрібно

2019-11-22 10:26 UTC, TArch64 commented on homeworks/pavel.fudko_darkwoolf10/homework_4/webpack.config.js
> +                test: /\.s[ac]ss$/i,
сумніваюсь що в одному проекті хтось буде використовувати scss та sass . Можна просто вказати /\.scss$/i

2019-11-22 15:44 UTC, TupotaValentyn commented on homeworks/pavel.fudko_darkwoolf10/homework_4/src/Singleton.js
> +        return this.instance;
![image](https://user-images.githubusercontent.com/39265433/69439480-bd6f8000-0d4f-11ea-9393-1f7cbffd41aa.png)

2019-11-26 16:44 UTC, TArch64 commented
Закрито по причині довгої відсутності активності

2019-11-26 16:44 UTC, closed without merging